# Generated by Django 4.1.7 on 2023-05-22 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_usermood_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermood",
            name="set_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
