# Generated by Django 4.1.2 on 2022-10-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_usermood_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
